spring.application.name=projeto-extensao

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/doces_com_amor?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:docescomamor}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


jwt.validity=${JWT_VALIDITY:3600}
jwt.secret=${JWT_SECRET:cHJvamV0by1kb2Nlcy1jb20tYW1vci1ncnVwby05LXNwdGVjaA==}

google.calendar.id=${GOOGLE_CALENDAR_ID:3db8bb13db53a3d6b5ce7c6c43795907d1d478f0ff226f066d11acc5c56b06f8@group.calendar.google.com}
google.calendar.credentials-path=${GOOGLE_CALENDAR_CREDENTIALS_PATH:}
